# Generated by Django 5.0.6 on 2024-07-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='msg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_text', models.CharField(max_length=1000)),
                ('msg_date', models.DateTimeField(verbose_name='date of post')),
            ],
        ),
    ]
