# Generated by Django 5.0.6 on 2024-07-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='msg',
            name='msg_like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='msg',
            name='msg_text',
            field=models.CharField(max_length=100),
        ),
    ]
