# Generated by Django 5.0.6 on 2024-07-27 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_comment_msg_msg_like_alter_msg_msg_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='post.msg'),
        ),
        migrations.AddField(
            model_name='msg',
            name='msg_title',
            field=models.CharField(default=str, max_length=20),
            preserve_default=False,
        ),
    ]
