# Generated by Django 5.0.6 on 2024-07-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_comment_post_msg_msg_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='msg',
            name='msg_know_more',
            field=models.BooleanField(default=False),
        ),
         migrations.RemoveField(
            model_name='comment',
            name='comment_date',
         ),
    ]
